name: Selenium Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:     #  enables manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🔥 ADD HERE (after Java setup)
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests (Headless)
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml -Dheadless=true

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/